services:
  - type: web
    name: 3d-reconstruction-app
    runtime: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
    startCommand: gunicorn app:app
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
