services:
  - type: web
    name: 3d-reconstruction-app
    runtime: python
    buildCommand: chmod +x build.sh;./build.sh
    startCommand: python3 -m gunicorn app:app
    plan: free
    region: oregon
    envVars:
      - key: FLASK_ENV
        value: production
